#!/bin/bash
#EGgPLant - Database Creator
echo "EGgPLant Database Creator V1.0 by Morgan Ellis and Owen Holland"

usage()
{
echo
echo "EcoGenetics Lab Pipeline Quality Plot Generator"
echo 
echo "Usage: eggdb -q -d [-h]"
echo "Example: eggdb -q 'COI[All Fields] AND Asterias amurensis [Organism]' -d 'AsteriasDB'"
echo "Options:"
echo "q     Query - The desired query to search. To get the correct syntax for the query, go to the NCBI site and perform the desired search. The query must be enclosed with quotation marks. If you have double quotation marks WITHIN the query the query MUST be enclosed with SINGLE quotaion marks"
echo "d     Database Name- The name for the database. NOTE: Spaces are not accepted."
echo "h     Help - Displays help readout"
}

#pass options
while getopts ":q:d:h s" opt; do
        case $opt in
        q) query="${OPTARG}"
        ;;
        d) db="$OPTARG"
        ;;
        h) usage
        exit
        ;;
	s) cat /usr/bin/.EGS
	exit
	;;
        \?) echo 
        echo "Invalid Option"
        usage
        exit
        ;;
        esac
done

if [ ! -d "$query" ]
	then
	echo "ERROR: No query supplied"
	usage
        exit
        else [ ! -d "$db" ]
        echo "Database name not supplied"
        usage
        exit
fi


mkdir "$db"/

#search for query

esearch -db nucleotide -query "$query" |
efetch -format fasta \
> "$db"/"$db".fasta

esearch -db nucleotide -query "$query" | 
efetch -format docsum |
xtract -pattern DocumentSummary -element AccessionVersion \
> "$db"/"$db"acc.txt

esearch -db nucleotide -query "$query" |
efetch -format docsum |
xtract -pattern DocumentSummary -element TaxId \
> "$db"/"$db"taxid.txt

#remove suffixes
awk '{print $1}' "$db".fasta

#Combind Files
paste "$db"/"$db"acc.txt "$db"/"$db"taxid.txt > "$db"/"$db"taxmap.txt

#Make Blast DB
makeblastdb -in "$db"/"$db".fasta -parse_seqids -taxid_map "$db"/"$db"taxmap.txt -title "$db" -dbtype nucl -out "$db"/"$db"

#Remove unnecessary files
rm "$db"/"$db"acc.txt "$db"/"$db"taxid.txt

#Export Path
cwd=$(pwd)
export BLASTDB="$cwd"/"$db" >& /dev/null || setenv BLASTDB "${BLASTDB}:"$cwd"/"$db""

echo
echo "***IMPORTANT***"
echo "To use your blast db after this terminal session you must run <export BLASTDB="$cwd"/"$db"> at the start of each session"
echo "This can also be added to your .bashrc"
	read -p "Export path to .bashrc ? (Y/N) "
	echo 
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	export export BLASTDB="$cwd"/"$db" >& /dev/null
	echo "export BLASTDB="$cwd"/"$db"" >> $HOME/.bashrc
	echo "Please restart the terminal"
	elif [[ $REPLY =~ ^[Nn]$ ]]; then
		echo "Please remember to add this to before running blastn each session"
	fi

echo "Finished"
