#!/bin/bash
# EGgPLant Quality Plot
echo "EGgPLant Qaulity Plots V1.0 by Morgan Ellis and Owen Holland"

usage()
{
echo
echo "EcoGenetics Lab Pipeline Quality Plot Generator"
echo 
echo "Usage: eggqual -d [-h]"
echo "Example: eggqual -d RawFastq"
echo "Options:"
echo "d     Directory - Directory where the raw reads are stored"
echo "h     Help - Displays help readout"
}

while getopts ":d:h s" opt; do
        case $opt in
        d) raw="${OPTARG}"
        ;;
        h) usage
        exit
        ;;
	s) cat /usr/bin/.EGS
	exit
	;;
        \?) echo 
        echo "Invalid Option"
        usage
        exit
        ;;
        esac
done

which R &> /dev/null
     	
if [ $? -ne 0 ]
	then
	echo "R not found. Please install R or run eggplant install script (install.eggplant.sh) before continuing"
	exit
fi

#Check if raw Dir exists
if [ ! -d "$raw" ]
	then
	echo "ERROR: Directory '$raw' Does Not Exist"
	exit
fi

#Check if "forward" directory exists, if present skip sorting step
if [ ! -d "forward/" ]
	then #sorting step
	mkdir forward
	cp "$raw"/*R1_001.fastq.gz forward/
		count=`ls  -1 "$raw"/*R2_001.fastq.gz 2>/dev/null | wc -l` ; 
		if [ $count != 0 ] #checks if Rawfastq has reverse reads
			then
			mkdir reverse
			cp "$raw"/*R2_001.fastq.gz reverse/
		fi
	mkdir outputs
fi

#Checks if seqs are paired ends and run relevant script
if [[ "$(uname)" == "Linux" ]];
	then
	read -p "Are the sequences PAIRED END READS (Y/N/C)?"
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		EGPEPQ
	elif [[ $REPLY =~ ^[Nn]$ ]]; then
		EGSEPQ
	elif [[ $REPLY =~ ^[Cc]$ ]]; then
		exit
	fi
elif [[ "$(uname)" == "Darwin" ]];
	then
	read -p "Are the sequences PAIRED END READS (Y/N/C)?"
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		EGPEPQM
	elif [[ $REPLY =~ ^[Nn]$ ]]; then
		EGSEPQM
	elif [[ $REPLY =~ ^[Cc]$ ]]; then
		exit
	fi
fi
