#!/usr/local/bin/Rscript
#EGgPLant Paired End Reads Quality Plot Generator - V1.0.1 - Mac OS
cat("EGgPLant Quality Plot Generator for Paired End Reads\n")

Sys.setenv(R_INSTALL_STAGED = FALSE)

cat("Setting Repository\n")
r = getOption("repos") 
r["CRAN"] = "http://cran.csiro.au/"
options(repos = r)
rm(r)
cat("Loading Packages\n")
if(!("devtools" %in% list.files(.libPaths()))) install.packages("devtools")
if(!("BiocManager" %in% list.files(.libPaths()))) install.packages("BiocManager")
if(!("dada2" %in% list.files(.libPaths()))) BiocManager::install("dada2")
library(dada2)

cat("Assigning Pathways\n")

pathF <- "forward/" 
pathR <- "reverse/" 

cat("Generating Quality Plots\n")

QplotF <- sort(list.files(pathF, pattern="fastq.gz", full.names = TRUE))
QplotR <- sort(list.files(pathR, pattern="fastq.gz", full.names = TRUE))

cat("Depending on the number of samples you have, this may take some time. Take a brain break!\nYour quality plots will be saved to your outputs folder.")

tiff('outputs/qPlot_fwd.tiff', units="in", width=8, height=6, res=600, compression = 'lzw',type='cairo')
plotQualityProfile(QplotF, aggregate = TRUE)
garbage <- dev.off()

tiff('outputs/qPlot_rev.tiff', units="in", width=8, height=6, res=600, compression = 'lzw',type='cairo')
plotQualityProfile(QplotR, aggregate = TRUE)
garbage <- dev.off()

cat("Finished\n")
