#!/usr/bin/Rscript
# EGgPLant Single End Reads - V4.1 - Linux OS
cat("EGgPLant for Single End Reads\n")

Sys.setenv(R_INSTALL_STAGED = FALSE) 

cat("Setting Repository\n")

r = getOption("repos") 
r["CRAN"] = "http://cran.csiro.au/"
options(repos = r)
rm(r)

cat("Loading packages\n")

if(!("optparse" %in% list.files(.libPaths()))) install.packages("optparse")
suppressPackageStartupMessages(require(optparse))

option_list <- list( 
	make_option(c("-t", "--fwdT"), action="store", default=0, type="character", help="truncate"),
    	make_option(c("-m", "--minR"), action="store", default=10, type='character', help="minimum number of reads permissible")
)
    opt = parse_args(OptionParser(option_list=option_list))


opt$m<-as.numeric(opt$minR)
opt$t<-as.numeric(opt$fwdT)


if(!("latticeExtra" %in% list.files(.libPaths()))) install.packages("latticeExtra")
if(!("devtools" %in% list.files(.libPaths()))) install.packages("devtools")
library(devtools)
if(!("insect" %in% list.files(.libPaths()))) devtools::install_github("shaunpwilkinson/insect")
if(!("BiocManager" %in% list.files(.libPaths()))) install.packages("BiocManager")
if(!("dada2" %in% list.files(.libPaths()))) BiocManager::install("dada2")
library(insect)
library(dada2)

cat("Assigning Pathways\n")
pathF <- "forward/" 

filtpathF <- file.path(pathF, "filtered")

fastqFs <- sort(list.files(pathF, pattern="fastq.gz"))

cat("Trimming and Filtering Sequences\n")

out <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs), truncLen=opt$t, maxEE=2, truncQ=2, maxN=0, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=FALSE)
head(out)

filtFs <- list.files(filtpathF, pattern="fastq.gz", full.names = TRUE)
sample.names <- sapply(strsplit(basename(filtFs), "_"), `[`, 1)
names(filtFs) <- sample.names

cat("Learning Error Rates\n")

errF <- learnErrors(filtFs, nbases=1e8, multithread=TRUE, verbose = TRUE)
mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names

cat("Dereplicating and Merging\n")


for(sam in sample.names) {
  cat("Processing:", sam, "\n")
  derepF <- derepFastq(filtFs[[sam]], verbose = TRUE)
  ddF <- dada(derepF, err=errF, multithread=TRUE, verbose = TRUE)
  merger <- makeSequenceTable(ddF)
  mergers[[sam]] <- merger
}


rm(derepF)

head(mergers)


cat("Making Sequence Table\n")

seqtab <- makeSequenceTable(mergers)

cat("Number of samples and ASVs\n")

dim(seqtab)
table(nchar(getSequences(seqtab)))

cat("Chimera Removal\n")

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE)

cat("Number of samples and ASVs\n")

dim(seqtab.nochim)
cat("Proportion of reads removed\n")
sum(seqtab.nochim)/sum(seqtab)

rownames(seqtab.nochim) <- sub("_R1$", "", rownames(seqtab.nochim))

cat("Setting Minimum Number of Reads\n")

colsums <- apply(seqtab.nochim, 2, sum)
discards <- colsums < opt$m
seqtab.nochim <- seqtab.nochim[, !discards]

cat("Writing CSV\n")
trans.seqtab <-t(seqtab.nochim)
write.csv(trans.seqtab, file = "outputs/Pipeline_Results.csv", row.names = TRUE)

cat("Writing fasta file\n")
x <- char2dna(colnames(seqtab.nochim))
names(x) <- paste0("ASV", seq_along(x))
#fas <- tempfile(fileext = ".fa", tmpdir = "outputs/")
writeFASTA(x, "outputs/Results.fa")


cat("Finished\n")
